name: Schelling workflow
on:
  push
jobs:
  pusher_checker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: pull repo
        uses: actions/checkout@v4
      -
        name: testing

        run: |
          chmod +x ./prereqs.sh ./test.sh ./build.sh
          ./prereqs.sh
          ./build.sh
          ./test.sh
