name: Schelling workflow
on:
  push
jobs:
  pusher_checker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: pull repo
        uses: actions/checkout@v4
      -
        name: testing

        run: |
          chmod +x ./prereqs.sh ./test.sh ./build.sh ./run.sh
          sudo apt update

          sudo apt upgrade -y 
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt install python3.11 -y
          sudo apt install python3-pip -y
          sudo pip install numpy matplotlib
          
          ./build.sh
          ./test.sh
          ./run.sh
